on:
  pull_request:
    types: [opened, reopened]
  workflow_call:
    secrets:
      asana-secret:
        required: true
      

jobs:
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    name: Create pull request attachments on Asana tasks
    steps:
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@latest
        id: postAttachment
        with:
          asana-secret: ${{ secrets.asana-secret }}
      - name: Log output status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
