---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Super Linter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [main, beta, staging]
  workflow_call:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Super Linter
    # Set the agent to run on
    runs-on: ubuntu-20.04

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Super Linter
        uses: github/super-linter@v4.9.4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_RUBY: true
          VALIDATE_YAML: true
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          RUBY_CONFIG_FILE: .rubocop.yml
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (/app/assets/javascripts/typeahead.bundle.js|package-lock.json)