name: Webpack Bundle Check
on:
  pull_request:
    branches: [main, beta, staging]
  workflow_call:
    inputs:
      ruby-version:
        type: string
        default: 3.0.x
    secrets:
      ssh-private-key:
        required: true
      sidekiq-pro-key:
        required: true
jobs:
  npm:
    name: "NPM"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up ssh
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.ssh-private-key }}
    - name: Install MySQL Client
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client libmysqlclient-dev
    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
    - name: Cache bundler
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle
      run: |
        gem install bundler --version 2.2.33
        bundle config gems.contribsys.com ${{ secrets.sidekiq-pro-key }}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: Setup node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14.x'
    - name: NPM checks - install and webpack
      run: |
        npm install