name: GitHub Security Alerts for Jira

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  workflow_call:
    secrets:
      gh-security-token:
        required: true
      jira-api-token:
        required: true

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ gh-security-token }}
          JIRA_TOKEN: ${{ jira-api-token }}
          JIRA_HOST: https://optimal-reach.atlassian.net
          JIRA_USER: devs@sreducationgroup.org
          JIRA_PROJECT: SE
          JIRA_ISSUE_TYPE: Security
          JIRA_RESTRICTED_COMMENT_ROLE: "*"
